### ISSUE TITLE
navLinks not working for Angular 9

### ISSUE THREAD

**Issue by Daniyar111** [fullcalendar/fullcalendar-angular#296] opened 2020-04-04 12:30 UTC
![navLinks](https://user-images.githubusercontent.com/38062694/78450625-c9763180-76a1-11ea-9fb2-26838bc55e73.gif)
Now, there is no error in console, but nothing happens... As you know you had an error in earlier release like `ERROR TypeError: Cannot read property 'emit' of undefined`, but now no error and don't navigate to day... And I downgraded dependencies to 4.2.0 and worked perfectly for Angular 8.. But today I upgraded Angular from 8 to 9 and fullcalendar for 4.4.0... yes, navLinks is not working -_-
And if I downgrade fullcalendar to 4.2.0 (where worked perfectly for Angular 8) I got this error: 
```
ERROR in The target entry-point "@fullcalendar/angular" has missing dependencies:
 - @fullcalendar/core/types/input-types
 - @fullcalendar/core/datelib/env
 - @fullcalendar/core/datelib/duration
 - @fullcalendar/core/datelib/formatting
 - @fullcalendar/core/datelib/date-range
 - @fullcalendar/core/datelib/locale
 - @fullcalendar/core/validation
 - @fullcalendar/core/structs/event-source
```
Dependencies of angular: 
    ```
"@angular-devkit/build-angular": "^0.901.0",
    "@angular/animations": "^9.1.0",
    "@angular/cdk": "^9.1.0",
    "@angular/cli": "^9.1.0",
    "@angular/common": "^9.1.0",
    "@angular/compiler": "^9.1.0",
    "@angular/compiler-cli": "^9.1.0",
    "@angular/core": "^9.1.0",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "^9.1.0",
    "@angular/material": "^9.1.0",
    "@angular/material-moment-adapter": "^9.1.0",
    "@angular/platform-browser": "^9.1.0",
    "@angular/platform-browser-dynamic": "^9.1.0",
    "@angular/platform-server": "^9.1.0",
    "@angular/router": "^9.1.0",
    "@angular/service-worker": "^9.1.0",
```
Dependecies of fullcalendar:
    ```
"@fullcalendar/angular": "^4.4.5-beta",
    "@fullcalendar/bootstrap": "^4.4.0",
    "@fullcalendar/core": "^4.4.0",
    "@fullcalendar/daygrid": "^4.4.0",
    "@fullcalendar/interaction": "^4.4.0",
    "@fullcalendar/list": "^4.4.0",
    "@fullcalendar/luxon": "^4.4.0",
    "@fullcalendar/moment": "^4.4.0",
    "@fullcalendar/moment-timezone": "^4.4.0",
    "@fullcalendar/timegrid": "^4.4.0",
```
component.html: 
```
<div class="fc fc-bootstrap4 fc-ltr" >
      <full-calendar
        #calendar
        defaultView="dayGridMonth"
        themeSystem="bootstrap"
        [events]="events"
        (eventRender)="eventRender($event)"
        [header]="header"
        [firstDay]="1"
        [locale]="locale"
        [buttonText]="buttonText"
        [plugins]="calendarPlugins"
        [selectable]="true"
        (dateClick)="onDateClick($event)"
        (select)="onDateSelect($event)"
        navLinks="true"
        (addEvent)="addEvent($event)"
        (eventClick)="onEventClick($event)"
        (datesRender)="onDatesRender($event)"
        ></full-calendar>
    </div>
```
component.ts ->
```
@ViewChild('calendar', {static: false}) calendarComponent: FullCalendarComponent;
  events: EventInput[] = [];
  calendarPlugins = [dayGridPlugin, timeGrigPlugin, interactionPlugin, bootstrapPlugin];
  header = {
    left: 'prev,next today',
    center: 'title',
    right: 'dayGridMonth,dayGridWeek,dayGridDay'
  };
  buttonText = {
    today:    'сегодня',
    month:    'месяц',
    week:     'неделя',
    day:      'день',
    list:     'список'
  };
  locale = ruLocale;
```

**Comment by bilelbensaoud** [comment] 2020-04-29 16:52
did you find the solution ? i have the same problem as you so please help me if you have any ideas

**Comment by Daniyar111** [comment] 2020-04-29 17:04
@bilelbensaoud no, just waiting 5th stable version with doc of fullcalendar, I guess it's global change for fullcalendar. It will be fiasko if new version will have more bugs than 4

**Comment by bilelbensaoud** [comment] 2020-04-29 17:29
@Daniyar111  ok thanks, we will wait for it

**Comment by Daniyar111** [comment] 2020-04-29 18:37
@bilelbensaoud you can install 5th beta version of fullcalendar.. now I don't have time to install and test it.. If you can, it will be so good to write feedback how it works on 5th version

**Comment by acerix** [comment] 2020-07-20 19:40
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

I believe this is a duplicate of this issue, `navLinks` is working in v5:
https://github.com/fullcalendar/fullcalendar-angular/issues/255

If there is still an issue, please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

**Closed by acerix** 2020-07-20 19:40 UTC
