### ISSUE TITLE
Update peer dependencies to enable angular 14

### ISSUE THREAD

**Issue by sergiotome** [fullcalendar/fullcalendar-angular#404] opened 2022-06-07 09:07 UTC
### Bug Reports
Angular complains about fullcalendar dependencies when upgrading to Angular 14. However, when using the --force attribute everything still works fine. This is something that we can do locally, but cannot do automatically on the CI/CD pipelines though, not allowing us to build the project when angular 14 is used.

### Feature Requests
Update peer dependencies in package.json to include angular 14

![image](https://user-images.githubusercontent.com/16870246/172342102-a61545d2-1ba1-4ccc-83ce-408aafdcf2fc.png)

**Comment by sergiotome** [comment] 2022-06-15 14:19
Any update on this?

**Comment by hadley8899** [comment] 2022-06-18 16:28
Bump on this

**Comment by nunoarruda** [comment] 2022-07-04 14:14
<img width="570" alt="Screenshot 2022-07-04 at 14 22 43" src="https://user-images.githubusercontent.com/1189149/177171875-f929c89d-a8c0-4d5d-84ae-d16eaadf6b5e.png">
Same problem here when using the latest version of @fullcalendar/angular + Angular 14.x + Node.js LTS 16.15.1.

I fixed my CI/CD pipelines by downgrading Node.js to 16.15.0. Not sure if this workaround will work for everybody else though.

**Comment by sergiotome** [comment] 2022-07-21 17:17
Angular released 14.1 already. Are there any updates on enabling support for that version any time soon?

**Comment by S1mo** [comment] 2022-07-22 10:19
UP

**Comment by mkoestner** [comment] 2022-07-27 09:41
UP

**Comment by criskrzysiu** [comment] 2022-08-03 08:56
there actually is a braking change that forces to patch node modules of fullcalendar removing css imports form main.js (multiple) - it can be done using patch-package to automate but is cumbersome.

**Comment by DvoraGWMobile** [comment] 2022-08-05 23:35
Hey, 
I'm getting this on ionic-angular 
```
Found: @angular/common@14.1.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"9 - 13" from @fullcalendar/angular@5.11.2
npm ERR! node_modules/@fullcalendar/angular
npm ERR!   @fullcalendar/angular@"^5.11.2" from the root project
```

Any help?

**Comment by sergiotome** [comment] 2022-08-08 10:01
> Hey, I'm getting this on ionic-angular
> 
> ```
> Found: @angular/common@14.1.1
> npm ERR! node_modules/@angular/common
> npm ERR!   @angular/common@"^14.0.0" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer @angular/common@"9 - 13" from @fullcalendar/angular@5.11.2
> npm ERR! node_modules/@fullcalendar/angular
> npm ERR!   @fullcalendar/angular@"^5.11.2" from the root project
> ```
> 
> This likely means that the library (@fullcalendar/angular/) which declares FullCalendarModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
> 
> Any help?

There are two issues here. The one in your screenshot refers to the issue discussed here, for which I haven't seen an update in more than a month. The other one is the issue discussed here: https://github.com/fullcalendar/fullcalendar-angular/issues/396#issue-1201633528

**Comment by morfems** [comment] 2022-08-08 14:58
Hello @arshaw,

I know that you are probably working on the ivy version, which is nice, but is it possible to release this [#408](https://github.com/fullcalendar/fullcalendar-angular/pull/408) as a minor version, and when the ivy version is ready, release it as major one, please ?

Also, the company I'm working at, uses the paid version, is it the same thing as the free one in terms of requesting new features/releases ? Because this library is the only one holding us from upgrading to Angular 14 and using all the new features.

Thanks in advance.

**Comment by nunoarruda** [comment] 2022-08-08 15:01
@morfems have you tried migrating from `@fullcalendar/angular` to `@fullcalendar/web-component`?

See: https://github.com/fullcalendar/fullcalendar-angular/issues/403#issuecomment-1205370948

**Comment by morfems** [comment] 2022-08-08 15:14
Thanks @nunoarruda for the suggestion 👍. Actually no, I didn't, I wasn't aware of the existence of this package. I think I am going to test it locally and wait for the stable version to use in prod.

**Comment by jonathankretzmer** [comment] 2022-08-10 14:33
Angular v14 instructions are here:
https://fullcalendar.io/docs/v6/angular

Using @beta versions of the web-component and plugins seems to work nicely.

**Comment by SiebeDom** [comment] 2022-09-05 12:45
We are using full calendar as a peer dependency of the PrimeNG Ultima theme.
We would like to upgrade to the latest version, but we don't want to use a @beta version.
Any idea when the final version will be released?

**Comment by sergiotome** [comment] 2022-09-13 07:26
It has been almost 4 months since Angular 14 was released and as of now we only have a beta version that works with it. Many people won't want to use a beta version of code in their production releases, and therefore, is there a roadmap about when a final solution will be available to support, not only Angular 14, but any future Angular release going forward (v15 will be out there soon!!)?

**Comment by rr-hornback** [comment] 2022-09-14 17:46
BUMP

**Comment by ng-druid** [comment] 2022-09-21 15:59
[We](https://www.cylitix.com/) are also anxiously awaiting the official production release compatible with v14.x. Thanks

**Comment by yelhouti** [comment] 2022-09-30 05:11
Did anyone make a pull request ?

**Comment by mvaljento** [comment] 2022-10-25 08:25
What's happening? Angular 14 has been available almost half a year now..

**Comment by morfems** [comment] 2022-11-03 14:48
After testing `@fullcalendar/web-component`, it works just fine, but there is no way we are going to prod with a beta version.

V6 in the roadmap was scheduled for Q3, we are now in Q4 and we have no information when the stable version will be available. The beta version was up for some time, why not ship it as stable if there are no regressions ?

It makes it hard to purchase more licenses or even recommend fullcalendar to others. And as others mentioned, angular v15 is almost here, and we are still putting on hold migrating to angular 14 because of this library alone. 

For now, all we ask for is some responses, you can't keep people hanging, we have our roadmaps too. Thanks

@arshaw

**Closed** 2022-11-15 17:47 UTC
Labels: Discussing

**Comment by arshaw** [comment] 2022-12-15 21:32
Release in [v6.0.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0)

**Comment by nicolacardi** [comment] 2023-02-17 11:29
@arshaw I have migrated angular to the latest version, which is now 15.1.5 and then tried to upgrade fullcalendar.

It works fine with all plugins (daygrid, list, timegrid, interaction) but fails on the @fullcalendar/angular  main update. 

```
code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: swapp-x@0.0.0
npm ERR! Found: @angular/common@15.1.5
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^15.1.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"9 - 14" from @fullcalendar/angular@5.11.4
npm ERR! node_modules/@fullcalendar/angular
npm ERR!   @fullcalendar/angular@"^5.11.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
I have gone through all this thread and the previous #403 but if it has to work without hacks or workarounds it would be a stable solution...
is there then any way to overcome this, possibly without workarounds? Thank you!!
